### ISSUE TITLE
Would you share the Pre-trained models and the test script?

### ISSUE THREAD

**Issue by HyuanTan** [utiasSTARS/cat-net#1]
Hi, thanks for share and your fantastic work!
I'm very interested in your project and would you share the Pre-trained models and the test script?
Thanks!

**Comment by HyuanTan** [comment]
According to the dataset and script you provide, I can already train the model and test on web camera.

Thanks!!

**Comment by amiltonwong** [comment]
Hi, @HyuanTan ,

Would you help to upload your trained model? Also, could you list the steps on how to perform the training and testing based on the author's script?

Thanks!
